### ISSUE TITLE
2D input for 1D Forecast

### ISSUE THREAD

**Issue by firmai** [timetoai/TimeDiffusion#1]
Hi, nice model, how would you adjust the inputs to receive multivariate data to forecast univariate data e.g., f(["litecoin", "ripple", "ethereum"]) = "bitcoin"

**Comment by timetoai** [comment]
Hi! Current framework concept allows working with multivariate data. You can train and forecast for all channels (e.g. prices), then extract required channel. But if you need `bitcoin` channel in output you also need to provide it in the input.

P.S. About your idea: you can use one of the base models, but you will need to create a new framework. I think you can combine the feature channels and noise as input and then remove the noise using the model with one output channel.
